# Generated by Django 3.2.5 on 2021-07-16 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_userip'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userip',
            options={},
        ),
        migrations.AddField(
            model_name='userip',
            name='count_get',
            field=models.PositiveIntegerField(default=0, verbose_name='GET'),
        ),
        migrations.AddField(
            model_name='userip',
            name='count_post',
            field=models.PositiveIntegerField(default=0, verbose_name='POST'),
        ),
    ]
