# Generated by Django 3.2.5 on 2021-07-17 11:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210716_2123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advuser',
            options={},
        ),
        migrations.AlterModelManagers(
            name='advuser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='advuser',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='advuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='advuser',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='advuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='advuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='advuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='advuser',
            name='username',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
